name: Preview CI/CD

on:
  pull_request:
    branches:
      - develop

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: Frontend

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: Frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: Frontend/

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      pull-requests: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Project Settings
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        id: deploy-vercel
        run: |
          vercel build --token=${{ env.VERCEL_TOKEN }}

          DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }})
          echo "preview_url=$DEPLOY_URL" >> $GITHUB_OUTPUT

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: 'YYYY년 MM월 DD일 HH시 mm분'
          utcOffset: '+09:00'

      - name: Comment PR with preview URL
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: preview-link
          message: |
            🧷 **배포 미리보기:** ${{ steps.deploy-vercel.outputs.preview_url }}
            ⏰ **최종 업데이트:** ${{ steps.current-time.outputs.formattedTime }}
