name: Sync Fork

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Agent for pushing to fork
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub to known hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push changes to fork
        run: |
          git remote add fork git@github.com:Yun-Jinwoo/global-nomad.git
          git push fork ${GITHUB_REF#refs/heads/} --force
